apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dep
spec: 
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: 
      app: dep-label
  template:
    metadata: 
      name: dep-pod
      labels:
        app: dep-label
    spec: 
      containers:
        - name: kube-cont01
          image: lohith1994/dockerrepo:2.0
